Sex from chi
Public-Health-Scotland/phsmethods pull request #45
Opened 2020-10-02 10:28 UTC by Moohan

Opening as draft pending comments in the issue.
Closes #43

2020-10-12 02:25 UTC, 080708km requested changes
Delete

2021-05-11 14:21 UTC, davidc92 commented
Hi James

I'm just getting round to looking at this now. Before I do a review I'd just like to understand the scope for this function a bit more because I'm not entirely convinced this is all that useful? The reason being, I don't know of any dataset that has chi on it that does not also have sex. I also have some questions around how accurate this is - how are people who are intersex or their sex is otherwise unknown accounted for here? 

D

2021-06-07 14:03 UTC, davidc92 requested changes
Just a few minor comments. While you're updating, just in the interest of brevity, can you re-knit the readme.rmd file so that the .md is in sync as part of this PR please? D

2021-06-07 14:03 UTC, davidc92 commented on DESCRIPTION
> +    person("James", "McMahon", email = "j.mcmahon1@nhs.net", role = "ctb")
These email addresses are all incorrect, can you kindly update them?

2021-06-07 14:03 UTC, davidc92 commented on R/chi.R
> +#' @param male_value,female_value optionally supply custom values for Male and Female. Note
Add a space

2021-06-07 14:03 UTC, davidc92 commented on R/chi.R
> +#' @param as_factor logical, optionally return as a factor with lables \code{'Male'}
labels

2021-06-07 15:50 UTC, Moohan commented on DESCRIPTION
> +    person("James", "McMahon", email = "j.mcmahon1@nhs.net", role = "ctb")
Done

2021-06-07 15:52 UTC, Moohan commented on R/chi.R
> +#' @param male_value,female_value optionally supply custom values for Male and Female. Note
Not done - no space means that that note applies to both of the parameters. Check the doc with `?sex_from_chi` and you'll see what I mean.

2021-06-07 15:52 UTC, Moohan commented on R/chi.R
> +#' @param as_factor logical, optionally return as a factor with lables \code{'Male'}
Done

2021-06-08 11:20 UTC, Moohan commented
Made most of the changes, see comment above.

I updated the `readme.rmd` and re-knitted, I got the same error again about proxy (#55) ... However, the `.md` file still updated and looks ok to me (both in markdown and if you look at it on GitHub for this branch). There were also merge conflicts for some reason which I resolved.

I also just added a short bit to the readme for this function, I'm pretty happy that they're in sync now.

2021-06-09 14:19 UTC, davidc92 approved these changes

2021-06-09 14:19 UTC, merged