age_calculate, dob_from_chi and age_from_chi added
Public-Health-Scotland/phsmethods pull request #74
Opened 2022-03-21 16:05 UTC by Tina815

2022-03-23 11:53 UTC, Moohan requested changes
Hey, I've not run any of the code, just checked through it on GitHub. If I get chance to run it I'll add some more comments but probably smarter to wait for you to check and implement any of my suggestions you agree with before I check again.

2022-03-23 11:53 UTC, Moohan commented on NEWS.md
> +
Add the new functions to the news.

2022-03-23 11:53 UTC, Moohan commented on R/age_calculate.R
> +                date_class = c("period", "duration"), round_down = TRUE){
I think some renaming would make be useful here. How about
```suggestion
age_at_date <- function(dob, age_date = Sys.time(), units = "years",
                date_class = c("period", "duration"), round_down = TRUE) {
```

I think the usual use case for this will be to calculate the age at a specific date, so it seems sensible to name the function and parameters with this in mind.

2022-03-23 11:53 UTC, Moohan commented on R/dob_from_chi.R
> +  }
```suggestion
  if (any(max_date > Sys.Date())) {
    max_date <- pmin(max_date, Sys.Date())
    warning("any 'max_date' which is in the future will be set to today.")
  }
```

2022-03-23 11:53 UTC, Moohan commented on R/dob_from_chi.R
> +  if (is.null(min_date)) min_date <- as.Date("1900-01-01")
I left this as a TODO but never did it... I'll send an email to the CHILLI team and see if they can answer it easily! Either way the comment should be removed.

2022-03-23 11:53 UTC, Moohan commented on R/dob_from_chi.R
> +  ))
Add in some comments to remind us/others in the future.
```suggestion
  guess_dob <- as.Date(dplyr::case_when(
    # Date is NA - missing, invalid or an invalid leap year date in 19XX.
    is.na(date_1900) ~ date_2000,
    # Invalid leap year date in 20XX.
    is.na(date_2000) ~ date_1900,
    # 20XX date is in the valid range and the 19XX date isn't.
    (date_2000 >= min_date & date_2000 <= max_date) &
      !(date_1900 >= min_date & date_1900 <= max_date) ~ date_2000,
    # 19XX date is in the valid range and the 20XX date isn't.
    (date_1900 >= min_date & date_1900 <= max_date) &
      !(date_2000 >= min_date & date_2000 <= max_date) ~ date_1900
  ))
```

2022-03-23 11:53 UTC, Moohan commented on tests/testthat/test-age_calculate.R
> +
Probably prudent to have some additional tests here e.g. counts of days with a leap day in it - "2020-02-20":"2020-03-01" should be 10 days.

2022-03-23 11:53 UTC, Moohan commented on R/age_calculate.R
> +  }
Explicitly return.
```suggestion
  age_interval <- dplyr::if_else(round_down,
      age_interval %/% unit_time,
    age_interval / unit_time)

  return(age_interval)
```

2022-03-23 11:53 UTC, Moohan commented on R/age_calculate.R
> +#' @param date_class Type of `lubridate` date class. Accepted arguments are "period" and "duration".
I'm not sure I understand the purpose of `date_class`. I would expect this function to return a numeric. What is the default return type and how does `date_class` change that?

2022-03-23 11:53 UTC, Moohan commented on R/dob_from_chi.R
> +  guess_age <- age_calculate(guess_dob, ref_date)
From my reading of `age_calculate` isn't the parameter `date_class` required? (see my other comment on `date_class`

2022-03-23 11:53 UTC, Moohan commented on tests/testthat/test-age_calculate.R
> +})
- [ ]  Add some tests for the other `date_class` option.
- [ ] Add some tests on the return type.
- [ ] Add some test for `round_down = FALSE` (`round_down = TRUE` isn't required here as it's the default.
- [ ] Add a test for start date after end date (i.e. negative age) - Could possibly include an error or warning for this? Maybe also warn for very large (>130) ages?

2022-03-28 14:21 UTC, Tina815 commented on R/age_calculate.R
> +                date_class = c("period", "duration"), round_down = TRUE){
I would prefer age_calculate as the name so would rather keep it in this way haha. I think arguments as start and end are clear enough to me so will just leave them.

2022-05-02 11:15 UTC, Moohan approved these changes

2022-05-02 12:35 UTC, merged